on: push
name: 🚀 Deploy function on push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  deploy-function:
    needs: test
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy function install
        run: doctl serverless install
      - name: Doctl connect function
        run: doctl serverless connect contact
      - name: Deploy function
        run: doctl serverless deploy .